//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCore.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAnnotationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusCore.Common.Resources.DataAnnotationText", typeof(DataAnnotationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person email.
        /// </summary>
        internal static string ClientDepartmentRequiredContactEmail {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person firstname.
        /// </summary>
        internal static string ClientDepartmentRequiredContactFirstName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person lastname.
        /// </summary>
        internal static string ClientDepartmentRequiredContactLastName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person phone.
        /// </summary>
        internal static string ClientDepartmentRequiredContactPhoneNumber {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a contact person title.
        /// </summary>
        internal static string ClientDepartmentRequiredContactTitle {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a department name.
        /// </summary>
        internal static string ClientDepartmentRequiredName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a client name.
        /// </summary>
        internal static string ClientRequiredName {
            get {
                return ResourceManager.GetString("ClientRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a domain name.
        /// </summary>
        internal static string DomainRequiredName {
            get {
                return ResourceManager.GetString("DomainRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter maximum 500 characters.
        /// </summary>
        internal static string GeneralMaximum500 {
            get {
                return ResourceManager.GetString("GeneralMaximum500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a email address.
        /// </summary>
        internal static string GeneralRequiredEmail {
            get {
                return ResourceManager.GetString("GeneralRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a firstname.
        /// </summary>
        internal static string GeneralRequiredFirstname {
            get {
                return ResourceManager.GetString("GeneralRequiredFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a lastname.
        /// </summary>
        internal static string GeneralRequiredLastname {
            get {
                return ResourceManager.GetString("GeneralRequiredLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string GeneralRequiredValidEmail {
            get {
                return ResourceManager.GetString("GeneralRequiredValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a title.
        /// </summary>
        internal static string InstallationAdministratorRequiredTitle {
            get {
                return ResourceManager.GetString("InstallationAdministratorRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a website name.
        /// </summary>
        internal static string WebsiteRequiredName {
            get {
                return ResourceManager.GetString("WebsiteRequiredName", resourceCulture);
            }
        }
    }
}
