//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCore.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusCore.Common.Resources.DataAnnotationText", typeof(DataAnnotationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string ClientDepartmentDisplayName {
            get {
                return ResourceManager.GetString("ClientDepartmentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person email.
        /// </summary>
        public static string ClientDepartmentRequiredContactEmail {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person firstname.
        /// </summary>
        public static string ClientDepartmentRequiredContactFirstName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person lastname.
        /// </summary>
        public static string ClientDepartmentRequiredContactLastName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact person phone.
        /// </summary>
        public static string ClientDepartmentRequiredContactPhoneNumber {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a contact person title.
        /// </summary>
        public static string ClientDepartmentRequiredContactTitle {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a department name.
        /// </summary>
        public static string ClientDepartmentRequiredName {
            get {
                return ResourceManager.GetString("ClientDepartmentRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Url.
        /// </summary>
        public static string ClientDisplayLogoUrl {
            get {
                return ResourceManager.GetString("ClientDisplayLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientDisplayName {
            get {
                return ResourceManager.GetString("ClientDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a client name.
        /// </summary>
        public static string ClientRequiredName {
            get {
                return ResourceManager.GetString("ClientRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a domain name.
        /// </summary>
        public static string DomainRequiredName {
            get {
                return ResourceManager.GetString("DomainRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string GeneralComparePassword {
            get {
                return ResourceManager.GetString("GeneralComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string GeneralDisplayAddress1 {
            get {
                return ResourceManager.GetString("GeneralDisplayAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string GeneralDisplayAddress2 {
            get {
                return ResourceManager.GetString("GeneralDisplayAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Passowrd.
        /// </summary>
        public static string GeneralDisplayConfirmPassword {
            get {
                return ResourceManager.GetString("GeneralDisplayConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string GeneralDisplayCountry {
            get {
                return ResourceManager.GetString("GeneralDisplayCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string GeneralDisplayCounty {
            get {
                return ResourceManager.GetString("GeneralDisplayCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GeneralDisplayDescription {
            get {
                return ResourceManager.GetString("GeneralDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GeneralDisplayEmail {
            get {
                return ResourceManager.GetString("GeneralDisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string GeneralDisplayFirstName {
            get {
                return ResourceManager.GetString("GeneralDisplayFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string GeneralDisplayLastName {
            get {
                return ResourceManager.GetString("GeneralDisplayLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string GeneralDisplayMobile {
            get {
                return ResourceManager.GetString("GeneralDisplayMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string GeneralDisplayPhoneNumber {
            get {
                return ResourceManager.GetString("GeneralDisplayPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string GeneralDisplayPostCode {
            get {
                return ResourceManager.GetString("GeneralDisplayPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GeneralDisplayTitle {
            get {
                return ResourceManager.GetString("GeneralDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string GeneralDisplayTown {
            get {
                return ResourceManager.GetString("GeneralDisplayTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter maximum 500 characters.
        /// </summary>
        public static string GeneralMaximum500 {
            get {
                return ResourceManager.GetString("GeneralMaximum500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a email address.
        /// </summary>
        public static string GeneralRequiredEmail {
            get {
                return ResourceManager.GetString("GeneralRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a firstname.
        /// </summary>
        public static string GeneralRequiredFirstname {
            get {
                return ResourceManager.GetString("GeneralRequiredFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a lastname.
        /// </summary>
        public static string GeneralRequiredLastname {
            get {
                return ResourceManager.GetString("GeneralRequiredLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        public static string GeneralRequiredNewPassword {
            get {
                return ResourceManager.GetString("GeneralRequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a title.
        /// </summary>
        public static string GeneralRequiredTitle {
            get {
                return ResourceManager.GetString("GeneralRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string GeneralRequiredValidEmail {
            get {
                return ResourceManager.GetString("GeneralRequiredValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters long, and at least 1 number.
        /// </summary>
        public static string GeneralValidationNewPassword {
            get {
                return ResourceManager.GetString("GeneralValidationNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string MembershipDisplayRoleName {
            get {
                return ResourceManager.GetString("MembershipDisplayRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a role name.
        /// </summary>
        public static string MembershipRequiredRoleName {
            get {
                return ResourceManager.GetString("MembershipRequiredRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a website name.
        /// </summary>
        public static string WebsiteRequiredName {
            get {
                return ResourceManager.GetString("WebsiteRequiredName", resourceCulture);
            }
        }
    }
}
