//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCore.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogCodeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogCodeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusCore.Common.Resources.LogCodeRes", typeof(LogCodeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System has been already installed, you can&apos;t run installation again..
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find current user or current user did not login..
        /// </summary>
        public static string C20 {
            get {
                return ResourceManager.GetString("C20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password you entered is incorrect..
        /// </summary>
        public static string C200 {
            get {
                return ResourceManager.GetString("C200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is already registered..
        /// </summary>
        public static string C201 {
            get {
                return ResourceManager.GetString("C201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is already exist..
        /// </summary>
        public static string C202 {
            get {
                return ResourceManager.GetString("C202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete select role because there are users exist in role..
        /// </summary>
        public static string C203 {
            get {
                return ResourceManager.GetString("C203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete system default role.
        /// </summary>
        public static string C204 {
            get {
                return ResourceManager.GetString("C204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id not found in ItemInSourceTree..
        /// </summary>
        public static string C205 {
            get {
                return ResourceManager.GetString("C205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has website..
        /// </summary>
        public static string C206 {
            get {
                return ResourceManager.GetString("C206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutofacFactory has not been intialized, have you called Initialize()?.
        /// </summary>
        public static string C50 {
            get {
                return ResourceManager.GetString("C50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUserProvider has not been intialized, have you called Initialize()?.
        /// </summary>
        public static string C51 {
            get {
                return ResourceManager.GetString("C51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Setting not exist or value type is wrong..
        /// </summary>
        public static string C60 {
            get {
                return ResourceManager.GetString("C60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Setting {0} not exist or value type is wrong..
        /// </summary>
        public static string C601 {
            get {
                return ResourceManager.GetString("C601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Setting already exist, can not create a new one..
        /// </summary>
        public static string C61 {
            get {
                return ResourceManager.GetString("C61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id not found in SourceTree.
        /// </summary>
        public static string C70 {
            get {
                return ResourceManager.GetString("C70", resourceCulture);
            }
        }
    }
}
