//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCore.Admin.UILogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminUIDataAnnotationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminUIDataAnnotationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusCore.Admin.UILogic.Resources.AdminUIDataAnnotationText", typeof(AdminUIDataAnnotationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string UserAccountComparePassword {
            get {
                return ResourceManager.GetString("UserAccountComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string UserAccountDisplayActivationToken {
            get {
                return ResourceManager.GetString("UserAccountDisplayActivationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Passowrd.
        /// </summary>
        public static string UserAccountDisplayConfirmPassword {
            get {
                return ResourceManager.GetString("UserAccountDisplayConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserAccountDisplayEmail {
            get {
                return ResourceManager.GetString("UserAccountDisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserAccountDisplayFirstName {
            get {
                return ResourceManager.GetString("UserAccountDisplayFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserAccountDisplayLastName {
            get {
                return ResourceManager.GetString("UserAccountDisplayLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passowrd.
        /// </summary>
        public static string UserAccountDisplayNewPassword {
            get {
                return ResourceManager.GetString("UserAccountDisplayNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserAccountDisplayPassword {
            get {
                return ResourceManager.GetString("UserAccountDisplayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string UserAccountDisplayPhoneNumber {
            get {
                return ResourceManager.GetString("UserAccountDisplayPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string UserAccountDisplayRememberMe {
            get {
                return ResourceManager.GetString("UserAccountDisplayRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string UserAccountDisplayTitle {
            get {
                return ResourceManager.GetString("UserAccountDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserAccountDisplayUserName {
            get {
                return ResourceManager.GetString("UserAccountDisplayUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string UserAccountDisplayWebsite {
            get {
                return ResourceManager.GetString("UserAccountDisplayWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a activation token from your email..
        /// </summary>
        public static string UserAccountRequiredActivationToken {
            get {
                return ResourceManager.GetString("UserAccountRequiredActivationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email..
        /// </summary>
        public static string UserAccountRequiredEmail {
            get {
                return ResourceManager.GetString("UserAccountRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a first name..
        /// </summary>
        public static string UserAccountRequiredFirstName {
            get {
                return ResourceManager.GetString("UserAccountRequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a last name..
        /// </summary>
        public static string UserAccountRequiredLastName {
            get {
                return ResourceManager.GetString("UserAccountRequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        public static string UserAccountRequiredNewPassword {
            get {
                return ResourceManager.GetString("UserAccountRequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string UserAccountRequiredPassword {
            get {
                return ResourceManager.GetString("UserAccountRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number..
        /// </summary>
        public static string UserAccountRequiredPhoneNumber {
            get {
                return ResourceManager.GetString("UserAccountRequiredPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a title..
        /// </summary>
        public static string UserAccountRequiredTitle {
            get {
                return ResourceManager.GetString("UserAccountRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email..
        /// </summary>
        public static string UserAccountValidationEmail {
            get {
                return ResourceManager.GetString("UserAccountValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters long, and at least 1 number.
        /// </summary>
        public static string UserAccountValidationNewPassword {
            get {
                return ResourceManager.GetString("UserAccountValidationNewPassword", resourceCulture);
            }
        }
    }
}
